version: '2'
services:
  zookeeper:
    image: zk:3.5
    container_name: zookeeper
    volumes:
      - ./zkdata:/data
    ports:
      - "2181:2181"
       
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka-demo
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.24.76.52
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka_log:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
 
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager-demo
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181