spring:
  application:
    name: kafka-demo
  cloud:
    stream:
      bindings:
        demo_input:
          destination: demo
          group: demo
        demo_output:
          destination: demo
          group: demo
      default-binder: kafka
  kafka:
    bootstrap-servers: 172.24.76.52:9092
    consumer:
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer


server:
  port: 9099
